#!/usr/bin/env python3
"""lib_tool.py

A script with multiple functions related to manipulating, organizing, and preparing IINA's lib dependencies. It is
intended to operate on libs generated by the Nix build process to process them for use in the app budle.

The build process requires considerable post-processing to organizes the chain of libs which IINA's executables depend
on, and to rewrite their internal references to each other so that they can be included in the app bundle in a portable
way and without conflict, and doing this in a consistent way which allows for compatibility with ongoing Xcode
development.

This tool automates this process by scanning dependencies, consolidating compatible versions & renaming them using a
set of well-defined ("canonical") names. This is useful to avoid multiple versions of the same lib being bundled,
and to reduce the set of libs to a manageable quantity which faciltates referencing the libs in the Xcode project.
It also replace Nix's hard-coded paths to /nix/store/ with relative paths within the app bundle, which is necessary to
package the app for distribution.

Mode `--canonicalize` (pseudocode outline):
--------------------------------------------
let name_variants_multimap = [base_id -> [compatibility_version -> [variant_basename -> variant_full_path]]]
let canonical_name_multimap = [base_id -> [compatibility_version -> canonical_name]]

I. First Pass: Assemble dependency metadata

For all deps, build name_variants_multimap:
1. Start searching libs in Frameworks directory (first CLI arg), then iteratively search their deps, then their deps'
   deps, etc., until all transitive libs have also been searched, and add all libs found to name_variants_multimap.
   Use a set of filenames to track which libs have already been searched to avoid duplicate work.
2. Search the executables in MacOS directory similarly, adding their deps to the map as well. This ensures that any libs
   which are only referenced by the executables and not by any of the libs in Frameworks are still included in the map.

For each lib being examined during the above search:
1. Get deps from each lib using `otool -L`, extracting base_id (name of lib before first `.`) & basename from ref path,
   and also parse compatibility_version.
   A. Look for entries which start with '/nix/store/' (indicating they are local libs which we need to process).
   B. Also look for entries which start with '@rpath/' (indicating they are already normalized, but it's useful to
      track them for error logging purposes).
   C. Always immediately simplify compatibility_version by removing useless trailing '.0' segments.
      This allows for direct string-based comparisons. Example: "8.0.0" is simplified to "8".
2. Insert each {base_id, compatibility_version, variant_basename, variant_full_path} into name_variants_multimap.

II. Compile canonical_name_multimap

For all entries in name_variants_multimap:
1. For each base_id, determine best canonical_name for each compatibility_version.
   The canonical name should be the filename with the highest version in it. If multiple versions are found with
   different formatting, use the most specific version available (i.e., favor trailing '.0' versions).
   Example: given the 3 variants: {'libfoo.2.dylib', 'libfoo.2.1.dylib', 'libfoo.2.1.0.dylib'}, the canonical name
   will be 'libfoo.2.1.0.dylib'.
   - Special workaround for 'libiconv':
     If a base_id has more than one compatibility_version, rename the canonical name for each to include its
     compatibility_version, to ensure both can be included without conflict.
2. Store best variant name in canonical_name_multimap.

III. Second Pass: Rename libs, rewrite lib references to use @rpath & cnames, add missing LC_RPATH entries

For all canonical names in canonical_name_multimap:
1. Copy best variant of each (base_id, compatibility_version) pairing to libStaging directory, Use the canonical name as
   the variant_basename to look up the source path in name_variants_multimap.

For all files in libStaging directory:
1. Change their install_name id to @rpath/canonical_name.
2. Add missing LC_RPATH entries pointing to @executable_path/../Frameworks.
3. Replace /opt/nix references with @rpath references using the canonical names from canonical_name_multimap.
4. Move the processed file back to lib directory.

For all executables in MacOS directory:
1. Add missing LC_RPATH entries pointing to @executable_path/../Frameworks.
2. Replace /opt/nix references with @rpath references using the canonical names from canonical_name_multimap.

Mode --add-canonical-links:
---------------------------
Same as (I) & (II) above, but instead of copying canonical libs to libStaging, just add symbolic links to them to the
lib directory (if file is already present, skip it). No modifications are made to the lib or executable files in this
mode.

This option is needed to prevent `xcodebuild` from failing when executed via the Nix build process.
"""

import os
import re
import sys
import stat
import argparse
import subprocess
import shutil
from typing import Callable, Optional

# --- Constants ---

LC_RPATH: str = '@executable_path/../Frameworks'
APP_FRAMEWORKS_RELPATH = "Contents/Frameworks"
APP_EXECUTABLES_RELPATH = "Contents/MacOS"

# Set of lib IDs to exclude.
# Skip 'libffi-trampoline' (apparently a typo of 'libffi-trampolines'?)
ID_BLACKLIST: set[str] = {'libffi-trampoline'}

# --- Command line options ---

def make_arg_parser() -> argparse.ArgumentParser:
  parser = argparse.ArgumentParser(description="Tool for manipulating & organizing IINA's libs & their dependencies for use in the app bundle. This script is mostly intended to be used as part of the IINA build process, and is not intended for manual use, though it can be called manually for debugging purposes. For those who just want to build the libs, start with {project_dir}/other/build_deps.py.")

  parser.add_argument('lib_dir', type=str,
      help=f"Path to the 'lib' or '$app_bundle/{APP_FRAMEWORKS_RELPATH}' directory"
  )

  parser.add_argument('executable_dir', type=str,
      help=f"Path to the 'executable' or '$app_bundle/{APP_EXECUTABLES_RELPATH}' directory"
  )

  group = parser.add_mutually_exclusive_group(required=True)
  group.add_argument('--canonicalize', action='store_true',
                     help="Renames all libs in Frameworks directory to their canonical names, and also adds all their transitive dependencies to the Frameworks directory using their canonical names. Also, for all libs found in Frameworks directory & all executables found in the MacOS directory, rewrites all `/nix/store` lib references to `@rpath` references with each lib's canonical name. Also adds missing LC_RPATH entries to all libs.")
  group.add_argument('--add-canonical-links', action='store_true',
                     help="Add symbolic links for any missing canonically named libs to the Frameworks directory.")
  group.add_argument('--merge-architectures', action='store_true',
                     help="Merge x86_64 & Apple Silicon files to create universal binaries.")
  group.add_argument('--print-only', action='store_true',
                     help="Search for all /nix/store references among all dependencies, print them, then exit without doing any modifications.")

  parser.add_argument('--purge', action='store_true',
                      help="Remove all non-canonical libs from Frameworks directory so that only canonical libs remain.")

  parser.add_argument('-v', '--verbose', action='store_true',
                      help="Use more verbose logging.")

  parser.add_argument('--archroot0', type=str,
                       help="Path to the first archroot (required when using --merge-architectures).")
  parser.add_argument('--archroot1', type=str,
                      help="Path to the second archroot (required when using --merge-architectures).")

  return parser

# --- String manipulation ---

# Simplifies a version string by removing any trailing '.0' segments.
def simplify_version(full_version: str) -> str:
  version = full_version
  while version.endswith('.0'):
    version = version[:-2]
  return version

# Extracts the base ID and basename from a file path. The base ID is the part of the filename before the first dot.
def parse_base(file_path: str) -> Optional[tuple[str, str]]:
  basename = os.path.basename(file_path)
  name_tokens = basename.split('.')
  if name_tokens:
      return (basename, name_tokens[0])

  print(f'⚠️ Could not derive base ID from path: {file_path}')
  return None

# --- Basic file system operations ---

# Set given file's permissions to R+W by the owner.
def ensure_file_is_writable(file_path: str):
  os.chmod(file_path, stat.S_IRUSR | stat.S_IWUSR)

# Returns a list of (base_name, full_path) tuples for all files in the given directory.
def ls_files_in_dir(dir_path: str) -> list[tuple[str, str]]:
  all_children: map[tuple[str, str]] = map(lambda name: (name, os.path.join(dir_path, name)), os.listdir(dir_path))
  return [child for child in all_children if os.path.isfile(child[1])]

# Filters the contents of `lib_dir` for files found which end in known lib suffix, calling `handler` for each.
def for_all_libs_in_lib_dir(lib_dir: str, handler: Callable[[str, str], None]):
  for base_name, file_path in ls_files_in_dir(lib_dir):
    if base_name.endswith('.dylib') or base_name.endswith('.so'):
      handler(base_name, file_path)

# Calls `handler` for each file found in `exec_dir` (does not currently do any filtering).
def for_all_executables_in_executable_dir(exec_dir: str, handler: Callable[[str, str], None]):
  for base_name, file_path in ls_files_in_dir(exec_dir):
    handler(base_name, file_path)

# --- Lib metadata extraction & manipulation ---

# Calls otool and install_name_tool
def ensure_lc_rpath_present(lib_path: str):
  result = subprocess.run(['otool', '-l', lib_path], capture_output=True, text=True)
  for line in result.stdout.splitlines():
    if LC_RPATH in line:
      print(f'✅ LC_RPATH correctly set → {lib_path}')
      return

  print(f'➕ LC_RPATH {LC_RPATH} → {lib_path}')
  subprocess.run(['install_name_tool', '-add_rpath', LC_RPATH, lib_path])

def rewrite_lib_entry(current_entry: str, to: str, bin_path: str):
  subprocess.run(['install_name_tool', '-change', current_entry, to, bin_path])

# Gets lib references in the given Mach-O lib or executable binary whose path starts with '/nix/store/'.
# - bin_path: file system path to the Mach-O lib or executable binary to be examined.
# - nix_store_handler: will be called for all entries beginning with '/nix/store/'.
# - rpath_handler: optional callback which, if provided, will be called for all entries beginning with '@rpath/'.
def otool_find_lib_refs(bin_path: str, nix_store_handler: Callable[[str, str, str, str], None], \
  rpath_handler: Optional[Callable[[str, str, str, str], None]] = None, print_all=False):

  ref_entry_pattern = r'(.*) \(compatibility version ([^,]+), current version ([^\)]+)\)'
  otool_result = subprocess.run(['otool', '-L', bin_path], capture_output=True, text=True)
  for line in  otool_result.stdout.splitlines():
    if print_all:
      print(line)

    # Skip header lines which just repeat the source file info.
    # We are interested in the lines under them which are indented.
    if len(line) > 0 and line[0].isspace():
      match = re.match(ref_entry_pattern, line.strip())
      if not match:
        continue

      ref_path = match.group(1)

      if rpath_handler and ref_path.startswith('@rpath/'):
        compat_version = simplify_version(match.group(2))
        current_version = simplify_version(match.group(3))
        rpath_handler(bin_path, ref_path, compat_version, current_version)
        continue

      # We only care about local libs, which start out generated by Nix
      if not ref_path.startswith('/nix/store/'):
        continue

      compat_version = simplify_version(match.group(2))
      current_version = simplify_version(match.group(3))
      nix_store_handler(bin_path, ref_path, compat_version, current_version)

# --- Classes ---

class LibMetaDB:
  # Map: {base_id: {variant_compatibility_version: {variant_basename: variant_full_path}}}
  # By assembling the data first, we can elimminate the (many) duplicates before doing ELF work which will speed things
  # up greatly.
  name_variants_map: dict[str, dict[str, dict[str, str]]] = {}
  # Keep track of @rpath entries separately. We can still use them to rewrite /nix/store entries in other libs, though
  # we don't have full paths for them so we shouldn't store them in the same map as the /nix/store entries, and we
  # can't strictly assume that every @rpath entry found was created by a previous run of this script.
  rpaths_map: dict[str, dict[str, str]] = {}

  log_verbose: bool

  def __init__(self, log_verbose: bool):
    self.log_verbose = log_verbose

  def __store_lib_variant(self,
                          base_id: str, variant_compat_version: str, variant_basename: str, variant_full_path: str):
    variants_map = self.name_variants_map.get(base_id, dict())
    variant_subversions_map = variants_map.get(variant_compat_version, dict())
    variant_subversions_map[variant_basename] = variant_full_path
    variants_map[variant_compat_version] = variant_subversions_map
    self.name_variants_map[base_id] = variants_map

  def __store_rpath_variant(self,
                            base_id: str, variant_compat_version: str, variant_basename: str):
    rpaths_map: dict[str, str] = self.rpaths_map.get(base_id, dict())
    existing_basename = rpaths_map.get(variant_compat_version, '')
    if existing_basename and existing_basename != variant_basename:
      # Potentially not good. Proceed anyway but emit warning.
      print(f'⚠️ Found multiple @rpath entries for id={base_id} compatVersion={variant_compat_version}: '
            + f'{existing_basename} and {variant_basename}')
    rpaths_map[variant_compat_version] = variant_basename
    self.rpaths_map[base_id] = rpaths_map

  def populate_from_disk(self, lib_dir: str, executable_dir: str, print_all: bool):
    print(f'Scanning for lib dependencies…')

    libs_searched: dict[str, bool] = {}

    def mark_unsearched(_, file_path):
      libs_searched[file_path] = False
    # Add libs in Frameworks directory to search list. These are the "roots" of our search.
    for_all_libs_in_lib_dir(lib_dir, mark_unsearched)

    # Add executables in MacOS directory to search list (more "roots" of our search).
    for_all_executables_in_executable_dir(executable_dir, mark_unsearched)

    # Here we want to get a survey of *all* canonical libs which need to be modified
    def nix_store_handler(_, ref_path, compat_version, current_version):
      if self.log_verbose:
        print(f'Found ref: {ref_path} compat: {compat_version} curr: {current_version}')
      base_tuple = parse_base(ref_path)
      if not base_tuple:
        return
      (ref_basename, base_id) = base_tuple
      if base_id in ID_BLACKLIST:
        print(f'Ref is in blacklist, skipping: {ref_path}')
        return
      if libs_searched.get(ref_path, False):
        # print(f'Ref already checked, skipping: {ref_path}')
        return
      # Need to search this ref for any transitive refs:
      libs_searched[ref_path] = False
      self.__store_lib_variant(base_id, compat_version, ref_basename, ref_path)

    def rpath_handler(_, ref_path, compat_version, current_version):
      base_tuple = parse_base(ref_path)
      if not base_tuple:
        return
      (ref_basename, ref_base_id) = base_tuple
      if ref_base_id in ID_BLACKLIST:
        print(f'Ref is in blacklist, skipping: {ref_path}')
        return

      if self.log_verbose:
        print(f'Found @rpath ref: {ref_path} compat: {compat_version} curr: {current_version}')
      self.__store_rpath_variant(ref_base_id, compat_version, ref_basename)

    # Use a loop to iteratively search as deep as needed into any transitive dependencies which are found. But we use
    # files_to_search to mark the files we've already examined and avoid duplicate work.
    while True:
      files_to_search: list[str] = [path for path, searched in libs_searched.items() if not searched]
      if not files_to_search:
        break

      for file_path in files_to_search:
        libs_searched[file_path] = True

        base_tuple = parse_base(file_path)
        if not base_tuple:
          continue
        (base_name, base_id) = base_tuple
        # See notes for blacklist above
        if base_id in ID_BLACKLIST:
          print(f'File is in blacklist, skipping: {file_path}')
          continue

        if self.log_verbose:
          print(f'Scanning: {file_path}')
        otool_find_lib_refs(file_path, nix_store_handler, rpath_handler, print_all=print_all)


class CanonicalNameDB:
  lib_db: LibMetaDB

  # Map: canonical_name_map = {base_id: {compat_version: canonical_name}}
  # Note: all versions must be simplified using simplify_version()! Otherwise string-based comparisons will fail.
  canonical_name_map: dict[str, dict[str, str]] = {}

  # The data in this class is all derived from lib_db. An instance of this class should not be created until after
  # lib_db is fully populated.
  def __init__(self, lib_db: LibMetaDB):
    self.lib_db = lib_db

    for base_id, variants_map in self.lib_db.name_variants_map.items():
      lib_version_count = len(variants_map)
      multiple_versions_found: bool = lib_version_count > 1
      if multiple_versions_found:
        print(f'Found multiple variants ({lib_version_count}) for {base_id}: {variants_map.keys()}')

      for variant_compat_ver, variant_subversions_map in variants_map.items():
        # Determine the best canonical name (higher, most specific version)
        best_variant_name: str = ''
        best_variant_version_split: list[str] = []
        for variant_name in variant_subversions_map.keys():
          variant_name_split = variant_name.split('.')
          if len(variant_name_split) < 2:
            print(f'⚠️ ERROR: failed to parse version from name, skipping: {variant_name}')
            continue
          last_elem = variant_name_split[-1]
          if last_elem != "dylib" and last_elem != "so":
            print(f'⚠️ ERROR: failed to parse version from name, skipping: {variant_name}')
            continue
          variant_version_split = variant_name_split[1:-1]

          if not best_variant_version_split:
            best_variant_name = variant_name
            best_variant_version_split = variant_version_split
            continue

          i = 0
          while i < len(variant_version_split):
            if (i >= len(best_variant_version_split)) or (variant_version_split[i] > best_variant_version_split[i]):
              best_variant_name = variant_name
              best_variant_version_split = variant_version_split
              break
            i += 1

        canonical_name: str
        if multiple_versions_found:
          # 2026-05-06 This is a workaround for a libiconv dependency issue (ffmpeg 8.0 + mpv 0.41), where different
          # libs require two different versions of it as a transitive dependency. These versions are internally
          # labelled v7 or v10, respectively, but both have the same filename (`libiconv.2.lib`). We resolve the
          # issue by renaming both files and rewriting all references to them using the new names.
          base_id_new: str = base_id + variant_compat_ver
          canonical_name = best_variant_name.replace(base_id, base_id_new)
          print(f'Deriving novel canonical name for {best_variant_name}, compatVersion {variant_compat_ver} '
                + f'→ {canonical_name}')
          best_variant_path: str = variant_subversions_map[best_variant_name]
          # Store the new canonical name back into the map, so we can find its source path when copying files.
          variant_subversions_map[canonical_name] = best_variant_path
        else:
          canonical_name = best_variant_name
          canonical_versions_map = self.canonical_name_map.get(base_id, dict())

        canonical_versions_map: dict[str, str] = self.canonical_name_map.get(base_id, dict())
        canonical_versions_map[variant_compat_ver] = canonical_name
        self.canonical_name_map[base_id] = canonical_versions_map

  def get_canonical_name(self, base_id: str, compat_version: str) -> Optional[str]:
    canonical_versions_map: dict[str, str] = self.canonical_name_map.get(base_id, {})
    if not canonical_versions_map:
      # Try rpaths
      canonical_versions_map = self.lib_db.rpaths_map.get(base_id, {})
      if not canonical_versions_map:
        print(f'⚠️ Could not find any versions for id={base_id} in canonical name map or rpaths map!')
        return None
    canonical_name = canonical_versions_map.get(compat_version, '')
    if not canonical_name:
      print(f'⚠️ Could not find canonical name for id={base_id} compatVersion={compat_version}')
      return None
    return canonical_name

  def for_all_canonical_names(self, handler: Callable[[str, str, str], None]):
    for base_id, canonical_versions_map in self.canonical_name_map.items():
      variants_map: dict[str, dict[str, str]] = self.lib_db.name_variants_map[base_id]
      for compat_version, canonical_name in canonical_versions_map.items():
        variant_subversions_map: dict[str, str] = variants_map[compat_version]
        src_path: str = variant_subversions_map.get(canonical_name, '')
        if not src_path:
          continue

        handler(canonical_name, compat_version, src_path)

# --- MAIN ---

def main():
  arg_parser: argparse.ArgumentParser = make_arg_parser()
  try:
    args = arg_parser.parse_args()
  except SystemExit:
    # argparse already prints the error; exit gracefully
    sys.exit(1)

  lib_dir = args.lib_dir
  executable_dir = args.executable_dir
  log_verbose = args.verbose
  if log_verbose:
    print(f'Parsed arguments: {args}')
    print(f'Verbose logging enabled')

  # --- FIRST PASS ---
  # Scan all libs with otool, collecting dependency metadata to populate lib_db

  lib_db = LibMetaDB(log_verbose=log_verbose)
  lib_db.populate_from_disk(lib_dir, executable_dir, print_all=args.print_only)

  for base_id, variants in lib_db.name_variants_map.items():
    print(f'Variants of {base_id}: {variants}')

  # Now compile the canonical name database, which will determine the best variant for each lib and store the
  # canonical name for each version.
  cname_db = CanonicalNameDB(lib_db)

  if args.print_only:
    print(f"⚠️ Exiting script now without modifying any files, as --print-only arg was provided.")
    return

  if args.add_canonical_links:
    print(f"Adding symlinks for missing canonically named libs…")

    def link_to_cname(canonical_name: str, _, src_path: str):
      dst_path = os.path.join(lib_dir, canonical_name)
      if os.path.isfile(dst_path):
        if log_verbose:
          print(f"Already exists: {dst_path}")
        return
      print(f"Adding link: {src_path} → {dst_path}")
      os.symlink(src_path, dst_path, target_is_directory=False)

    cname_db.for_all_canonical_names(link_to_cname)
    print(f"Adding symlinks: done")
    return

  if args.merge_architectures:
    print(f'🔍 Merging binaries across architectures')

    if not args.archroot0 or not args.archroot1:
      print(f'⚠️ Both --archroot0 and --archroot1 are required when --merge-architectures is given')
      exit(1)

    def merge_bin(basename, path0, path1, dst_dir):
      arm64 = ''
      x86_64 = ''
      for filename in [path0, path1]:
        stdoutput = subprocess.run(['lipo', '-info', filename], capture_output=True, text=True).stdout
        if stdoutput.startswith('Non-fat'):
          if 'x86_64' in stdoutput:
            x86_64 = filename
          elif 'arm64' in stdoutput:
            arm64 = filename
          else:
            print(f'⚠️ Failed to parse lipo -info for non-fat file, skipping: {filename}')
            continue
        elif ('Architectures in the fat file' in stdoutput) and ('arm64' in stdoutput) and ('x86_64' in stdoutput):
          # If only one arch available, leave it alone
          x86_64 = filename
          arm64 = filename
          break
        else:
          print(f'⚠️ Failed to parse lipo -info for file, skipping: {filename}')
          continue

      if not arm64 or not x86_64:
        print(f'✅ Skipping single-arch {basename}')
        return

      tmpfile=f'{basename}.universal.tmp'

      # Use copy2 to preserve all file metadata with the copy
      if arm64 == x86_64:
        # Already universal binary
        print(f'✅ Already dual-arch: {basename}')
        shutil.copy2(arm64, tmpfile)
      else:
        print(f'🔨 Merging {basename}')
        subprocess.run(['lipo', '-create', '-arch', 'arm64', arm64, '-arch', 'x86_64', x86_64, '-output', tmpfile])

      dst_path = os.path.join(dst_dir, basename)
      shutil.copy2(tmpfile, dst_path)

    # Merge lib dirs
    libs0 = os.path.join(args.archroot0, APP_FRAMEWORKS_RELPATH)
    libs1 = os.path.join(args.archroot1, APP_FRAMEWORKS_RELPATH)

    def merge_lib(lib_basename, _):
      path0 = os.path.join(libs0, lib_basename)
      path1 = os.path.join(libs1, lib_basename)
      print(f'Merging libs in: [{path0}, {path1}]')
      merge_bin(lib_basename, path0, path1, lib_dir)

    for_all_libs_in_lib_dir(lib_dir, merge_lib)

    # Merge executable dirs

    exe0 = os.path.join(args.archroot0, APP_FRAMEWORKS_RELPATH)
    exe1 = os.path.join(args.archroot1, APP_FRAMEWORKS_RELPATH)

    def merge_exe(exe_basename, _):
      path0 = os.path.join(exe0, exe_basename)
      path1 = os.path.join(exe1, exe_basename)
      print(f'Merging executables in: [{path0}, {path1}]')
      merge_bin(exe_basename, path0, path1, executable_dir)

    for_all_executables_in_executable_dir(executable_dir, merge_exe)

    print(f'🔍 Merging binaries across architectures: done')
    # Fall through and canonicalize the merged files.

  print(f"Canonicalizing libs in {lib_dir}…")
  # Create libStaging, then copy all libs to be processed into it.
  # This side-steps any thorny issues which might be caused by symlinks, makes purging Frameworks directory easier.
  lib_staging_dir_path = os.path.join(lib_dir, '../libStaging')
  os.makedirs(lib_staging_dir_path, exist_ok=True)
  print(f'Copying libs into {lib_staging_dir_path}')

  # Total count of libs copied, with different versions of the same lib counted as multiple.
  copied_libs_count: int = 0

  def copy_to_cname(canonical_name: str, compat_version: str, src_path: str):
    print(f'Canonical name for v{compat_version}: {canonical_name}')
    dst_path = os.path.join(lib_staging_dir_path, canonical_name)
    shutil.copyfile(src_path, dst_path)
    nonlocal copied_libs_count
    copied_libs_count += 1

  cname_db.for_all_canonical_names(copy_to_cname)
  print(f'Copied {copied_libs_count} libs into {lib_staging_dir_path}')

  # (Optional if "--purge" is specified). Removes unused lib files and links from Frameworks directory.
  # Note: this is not recursive. Sparkle.framework and any other directories will be untouched.
  # This step should not be used when building the IINA universal binary because arch-specific libs which have
  # already been processed may not be present in our data structures, and thus not moved to libStaging,
  # but they would still be deleted from Frameworks if --purge is used.
  if args.purge:
    print(f'Removing old lib files and links from {lib_dir}')
    old_lib_links = [f for f in os.listdir(lib_dir) if os.path.islink(os.path.join(lib_dir, f))]
    for old_lib_link in old_lib_links:
      link_path = os.path.join(lib_dir, old_lib_link)
      os.unlink(link_path)
    for _, oldlib_path in ls_files_in_dir(lib_dir):
      os.remove(oldlib_path)

  # --- SECOND PASS ---
  # Add missing LC_RPATH entries, rewrite lib references to use @rpath & canonical names.

  def nix_store_handler(current_file_path, ref_path, compat_version, _):
    base_tuple = parse_base(ref_path)
    if not base_tuple:
      return
    (_, base_id) = base_tuple
    sub_canonical_name = cname_db.get_canonical_name(base_id, compat_version)
    if not sub_canonical_name:
      return
    replacement_path = f'@rpath/{sub_canonical_name}'
    print(f"🔗 Repointing subdep for {os.path.basename(current_file_path)}: {ref_path} → {replacement_path}")
    rewrite_lib_entry(ref_path, replacement_path, current_file_path)

  # Process the libs in libStaging directory.
  # After each file is processed, it is moved from libStaging to Frameworks.
  print(f'🔧 Normalizing libs in {lib_staging_dir_path} & moving each to {os.path.basename(lib_dir)}')
  def normalize_lib(lib_basename, lib_path):
    print(f'Processing: {lib_basename}')
    print(f"✏️ Setting install_name id on {lib_basename}")
    subprocess.run(['install_name_tool', '-id', f'@rpath/{lib_basename}', lib_path])
    otool_find_lib_refs(lib_path, nix_store_handler)

    shutil.move(lib_path, os.path.join(lib_dir, lib_basename))

  for_all_libs_in_lib_dir(lib_staging_dir_path, normalize_lib)

  # Remove libStaging now that all libs have been transferred.
  shutil.rmtree(lib_staging_dir_path)

  # Now process the executable binaries in MacOS directory.
  print(f'🔧 Normalizing executables in {executable_dir}')
  def normalize_exe(exe_base_name, exe_path):
    print(f'Processing: {exe_base_name}')
    ensure_lc_rpath_present(exe_path)
    otool_find_lib_refs(exe_path, nix_store_handler)

  for_all_executables_in_executable_dir(executable_dir, normalize_exe)

  print(f"Canonicalizing libs: done")

if __name__ == '__main__':
    main()
