#!/usr/bin/env python3
"""lib_tool.py

A script with multiple functions related to manipulating, organizing, and preparing IINA's lib dependencies. It is
intended to operate on libs generated by the Nix build process to process them for use in the app budle.

The build process requires considerable post-processing to organizes the chain of libs which IINA's executables depend
on, and to rewrite their internal references to each other so that they can be included in the app bundle in a portable
way and without conflict, and doing this in a consistent way which allows for compatibility with ongoing Xcode
development.

This tool automates this process by scanning dependencies, consolidating compatible versions & renaming them using a
set of well-defined ("canonical") names. This is useful to avoid multiple versions of the same lib being bundled,
and to reduce the set of libs to a manageable quantity which faciltates referencing the libs in the Xcode project.
It also replace Nix's hard-coded paths to /nix/store/ with relative paths within the app bundle, which is necessary to
package the app for distribution.

Mode `--canonicalize` (pseudocode outline):
--------------------------------------------
let name_variants_multimap = [base_id -> [compatibility_version -> [variant_basename -> variant_full_path]]]
let canonical_name_multimap = [base_id -> [compatibility_version -> canonical_name]]

I. First Pass: Assemble dependency metadata

For all deps, build name_variants_multimap:
1. Start searching libs in Frameworks directory (first CLI arg), then iteratively search their deps, then their deps'
   deps, etc., until all transitive libs have also been searched, and add all libs found to name_variants_multimap.
   Use a set of filenames to track which libs have already been searched to avoid duplicate work.
2. Search the executables in MacOS directory similarly, adding their deps to the map as well. This ensures that any libs
   which are only referenced by the executables and not by any of the libs in Frameworks are still included in the map.

For each lib being examined during the above search:
1. Get deps from each lib using `otool -L`, extracting base_id (name of lib before first `.`) & basename from ref path,
   and also parse compatibility_version.
   A. Look for entries which start with '/nix/store/' (indicating they are local libs which we need to process).
   B. Also look for entries which start with '@rpath/' (indicating they are already normalized, but it's useful to
      track them for error logging purposes).
   C. Always immediately simplify compatibility_version by removing useless trailing '.0' segments.
      This allows for direct string-based comparisons. Example: "8.0.0" is simplified to "8".
2. Insert each {base_id, compatibility_version, variant_basename, variant_full_path} into name_variants_multimap.

II. Compile canonical_name_multimap

For all entries in name_variants_multimap:
1. For each base_id, determine best canonical_name for each compatibility_version.
   The canonical name should be the filename with the highest version in it. If multiple versions are found with
   different formatting, use the most specific version available (i.e., favor trailing '.0' versions).
   Example: given the 3 variants: {'libfoo.2.dylib', 'libfoo.2.1.dylib', 'libfoo.2.1.0.dylib'}, the canonical name
   will be 'libfoo.2.1.0.dylib'.
   - Special workaround for 'libiconv':
     If a base_id has more than one compatibility_version, rename the canonical name for each to include its
     compatibility_version, to ensure both can be included without conflict.
2. Store best variant name in canonical_name_multimap.

III. Second Pass: Rename libs, rewrite lib references to use @rpath & cnames, add missing LC_RPATH entries

For all canonical names in canonical_name_multimap:
1. Copy best variant of each (base_id, compatibility_version) pairing to libStaging directory, Use the canonical name as
   the variant_basename to look up the source path in name_variants_multimap.

For all files in libStaging directory:
1. Change their install_name id to @rpath/canonical_name.
2. Add missing LC_RPATH entries pointing to @executable_path/../Frameworks.
3. Replace /opt/nix references with @rpath references using the canonical names from canonical_name_multimap.
4. Move the processed file back to lib directory.

For all executables in MacOS directory:
1. Add missing LC_RPATH entries pointing to @executable_path/../Frameworks.
2. Replace /opt/nix references with @rpath references using the canonical names from canonical_name_multimap.

Mode --add-canonical-links:
---------------------------
Same as (I) & (II) above, but instead of copying canonical libs to libStaging, just add symbolic links to them to the
lib directory (if file is already present, skip it). No modifications are made to the lib or executable files in this
mode.

This option is needed to prevent `xcodebuild` from failing when executed via the Nix build process.
"""

import os
import re
import sys
import stat
import argparse
import subprocess
import shutil
from typing import Callable, Optional

# --- Constants ---

LC_RPATH: str = '@executable_path/../Frameworks'
APP_FRAMEWORKS_RELPATH = "Contents/Frameworks"
APP_EXECUTABLES_RELPATH = "Contents/MacOS"

# Set of lib IDs to exclude.
# Skip 'libffi-trampoline' (apparently a typo of 'libffi-trampolines'?)
ID_BLACKLIST: set[str] = {'libffi-trampoline'}
USR_LIB_WHITELIST: dict[str, tuple[str, str]] = {
  'libiconv': ('7', '/usr/lib/libiconv.2.dylib'),
  'libz': ('1', '/usr/lib/libz.1.dylib')
}

# --- Command line options ---

def make_arg_parser() -> argparse.ArgumentParser:
  parser = argparse.ArgumentParser(description="Tool for manipulating & organizing IINA's libs & their dependencies for use in the app bundle. This script is mostly intended to be used as part of the IINA build process, and is not intended for manual use, though it can be called manually for debugging purposes. For those who just want to build the libs, start with {project_dir}/other/build_deps.py.")

  parser.add_argument('lib_dir', type=str,
      help=f"Path to the 'lib' or '$app_bundle/{APP_FRAMEWORKS_RELPATH}' directory"
  )

  parser.add_argument('executable_dir', type=str,
      help=f"Path to the 'executable' or '$app_bundle/{APP_EXECUTABLES_RELPATH}' directory"
  )

  group = parser.add_argument_group()
  group.add_argument('--canonicalize', action='store_true',
                     help="Renames all libs in Frameworks directory to their canonical names, and also adds all their transitive dependencies to the Frameworks directory using their canonical names. Also, for all libs found in Frameworks directory & all executables found in the MacOS directory, rewrites all `/nix/store` lib references to `@rpath` references with each lib's canonical name. Also adds missing LC_RPATH entries to all libs.")
  group.add_argument('--merge-architectures', action='store_true',
                     help="Merge x86_64 & Apple Silicon files to create universal binaries.")
  group.add_argument('--print-only', action='store_true',
                     help="Search for all /nix/store references among all dependencies, print them, then exit without doing any modifications.")

  parser.add_argument('--prune', action='store_true',
                      help="Remove all non-canonical libs from Frameworks directory so that only canonical libs remain.")

  parser.add_argument('-v', '--verbose', action='store_true',
                      help="Use more verbose logging.")

  parser.add_argument('--archroot0', type=str,
                       help="Path to the first archroot (required when using --merge-architectures).")
  parser.add_argument('--archroot1', type=str,
                      help="Path to the second archroot (required when using --merge-architectures).")

  return parser

# --- String manipulation ---

# Simplifies a version string by removing any trailing '.0' segments.
def simplify_version(full_version: str) -> str:
  version = full_version
  while version.endswith('.0'):
    version = version[:-2]
  return version

# Extracts the base ID and basename from a file path. The base ID is the part of the filename before the first dot.
def parse_base(file_path: str) -> Optional[tuple[str, str]]:
  basename = os.path.basename(file_path)
  name_tokens = basename.split('.')
  if name_tokens:
      return (basename, name_tokens[0])

  print(f'⚠️ Could not derive base ID from path: {file_path}')
  return None

# --- Basic file system operations ---

# Set given file's permissions to R+W by the owner.
def ensure_file_is_writable(file_path: str):
  os.chmod(file_path, stat.S_IRUSR | stat.S_IWUSR)

# Returns a list of (base_name, full_path) tuples for all files in the given directory.
def ls_files_in_dir(dir_path: str) -> list[tuple[str, str]]:
  all_children: map[tuple[str, str]] = map(lambda name: (name, os.path.join(dir_path, name)), os.listdir(dir_path))
  return [child for child in all_children if os.path.isfile(child[1])]

# Filters the contents of `lib_dir` for files found which end in known lib suffix, calling `handler` for each.
def for_all_libs_in_lib_dir(lib_dir: str, handler: Callable[[str, str], None]):
  for base_name, file_path in ls_files_in_dir(lib_dir):
    if base_name.endswith('.dylib') or base_name.endswith('.so'):
      handler(base_name, file_path)

# Calls `handler` for each file found in `exec_dir` (does not currently do any filtering).
def for_all_executables_in_executable_dir(exec_dir: str, handler: Callable[[str, str], None]):
  for base_name, file_path in ls_files_in_dir(exec_dir):
    handler(base_name, file_path)

# --- Lib metadata extraction & manipulation ---

# Calls otool and install_name_tool
def fix_lc_rpath(lib_path: str):
  has_rpath = False
  has_correct_rpath = False
  rpath_path_pattern = r'\s+path (/nix/store/.+) \(offset \d+\)'
  result = subprocess.run(['otool', '-l', lib_path], capture_output=True, text=True)
  for line in result.stdout.splitlines():
    if LC_RPATH in line:
      has_correct_rpath = True
    else:
      match = re.match(rpath_path_pattern, line)
      if not match:
        continue
      has_rpath = True
      rpath = match.group(1)
      print(f'➖ Removing incorrect LC_RPATH from {lib_path} ↛ "{rpath}"')
      subprocess.run(['install_name_tool', '-delete_rpath', rpath, lib_path])

  if has_correct_rpath:
    print(f'✅ Has correct LC_RPATH: {lib_path}')
    return

  if has_rpath:
    print(f'➕ LC_RPATH {LC_RPATH} → {lib_path}')
    subprocess.run(['install_name_tool', '-add_rpath', LC_RPATH, lib_path])

def rewrite_lib_reference(current_ref: str, to: str, bin_path: str):
  subprocess.run(['install_name_tool', '-change', current_ref, to, bin_path])

# Gets lib references in the given Mach-O lib or executable binary whose path starts with '/nix/store/'.
# - bin_path: file system path to the Mach-O lib or executable binary to be examined.
# - handle_nix_store: will be called for all entries beginning with '/nix/store/'.
# - handle_rpath: optional callback which, if provided, will be called for all entries beginning with '@rpath/'.
def otool_find_lib_refs(bin_path: str, handle_nix_store: Callable[[str, str, str, str], None], \
  handle_rpath: Optional[Callable[[str, str, str, str], None]] = None, print_all=False):

  ref_entry_pattern = r'(.*) \(compatibility version ([^,]+), current version ([^\)]+)\)'
  otool_result = subprocess.run(['otool', '-L', bin_path], capture_output=True, text=True)
  for line in  otool_result.stdout.splitlines():
    if print_all:
      print(line)

    # Skip header lines which just repeat the source file info.
    # We are interested in the lines under them which are indented.
    if len(line) > 0 and line[0].isspace():
      match = re.match(ref_entry_pattern, line.strip())
      if not match:
        continue

      ref_path = match.group(1)

      if handle_rpath and ref_path.startswith('@rpath/'):
        compat_version: str = simplify_version(match.group(2))
        current_version: str = simplify_version(match.group(3))
        handle_rpath(bin_path, ref_path, compat_version, current_version)
        continue

      # We only care about local libs, which start out generated by Nix
      if not ref_path.startswith('/nix/store/'):
        continue

      compat_version = simplify_version(match.group(2))
      current_version = simplify_version(match.group(3))
      handle_nix_store(bin_path, ref_path, compat_version, current_version)


# Class: LibMetaDB
# This class is responsible for scanning the libs in the Frameworks directory and their transitive dependencies to build
# a map of all the lib variants found, organized by their base ID and compatibility version. This metadata is used to
# determine the canonical name for each lib, which is then used to copy the libs to the libStaging directory and rewrite
# their references.
class LibMetaDB:
  lib_dir_path: str
  executable_dir_path: str

  # Map: {base_id: {variant_compatibility_version: {variant_basename: variant_full_path}}}
  # By assembling the data first, we can elimminate the (many) duplicates before doing ELF work which will speed things
  # up greatly.
  name_variants_map: dict[str, dict[str, dict[str, str]]] = {}
  # Keep track of @rpath entries separately. We can still use them to rewrite /nix/store entries in other libs, though
  # we don't have full paths for them so we shouldn't store them in the same map as the /nix/store entries, and we
  # can't strictly assume that every @rpath entry found was created by a previous run of this script.
  rpaths_map: dict[str, dict[str, str]] = {}

  log_verbose: bool

  def __init__(self, lib_dir_path: str, executable_dir_path: str, log_verbose: bool):
    self.lib_dir_path = lib_dir_path
    self.executable_dir_path = executable_dir_path
    self.log_verbose = log_verbose

  def __store_lib_variant(self,
                          base_id: str, variant_compat_version: str, variant_basename: str, variant_full_path: str):
    variants_map = self.name_variants_map.get(base_id, dict())
    variant_subversions_map = variants_map.get(variant_compat_version, dict())
    variant_subversions_map[variant_basename] = variant_full_path
    variants_map[variant_compat_version] = variant_subversions_map
    self.name_variants_map[base_id] = variants_map

  def __store_rpath_variant(self,
                            base_id: str, variant_compat_version: str, variant_basename: str):
    rpaths_map: dict[str, str] = self.rpaths_map.get(base_id, dict())
    existing_basename = rpaths_map.get(variant_compat_version, '')
    if existing_basename and existing_basename != variant_basename:
      # Potentially not good. Proceed anyway but emit warning.
      print(f'⚠️ Found multiple @rpath entries for id={base_id} compatVersion={variant_compat_version}: '
            + f'{existing_basename} and {variant_basename}')
    rpaths_map[variant_compat_version] = variant_basename
    self.rpaths_map[base_id] = rpaths_map

  def populate_from_disk(self, print_all: bool):
    print(f'Scanning for lib dependencies…')

    libs_searched: dict[str, bool] = {}

    def mark_unsearched(_, file_path):
      libs_searched[file_path] = False
    # Add libs in Frameworks directory to search list. These are the "roots" of our search.
    for_all_libs_in_lib_dir(self.lib_dir_path, mark_unsearched)

    # Add executables in MacOS directory to search list (more "roots" of our search).
    for_all_executables_in_executable_dir(self.executable_dir_path, mark_unsearched)

    # Here we want to get a survey of *all* canonical libs which need to be modified
    def handle_nix_store(_, ref_path, compat_version, current_version):
      if self.log_verbose:
        print(f'Found ref: {ref_path} compat: {compat_version} curr: {current_version}')
      base_tuple = parse_base(ref_path)
      if not base_tuple:
        return
      (ref_basename, base_id) = base_tuple
      if base_id in ID_BLACKLIST:
        print(f'Ref is in blacklist, skipping: {ref_path}')
        return
      if libs_searched.get(ref_path, False):
        # print(f'Ref already checked, skipping: {ref_path}')
        return
      # Need to search this ref for any transitive refs:
      libs_searched[ref_path] = False
      self.__store_lib_variant(base_id, compat_version, ref_basename, ref_path)

    def handle_rpath(_, ref_path, compat_version, current_version):
      base_tuple = parse_base(ref_path)
      if not base_tuple:
        return
      (ref_basename, ref_base_id) = base_tuple
      if ref_base_id in ID_BLACKLIST:
        print(f'Ref is in blacklist, skipping: {ref_path}')
        return

      if self.log_verbose:
        print(f'Found @rpath ref: {ref_path} compat: {compat_version} curr: {current_version}')
      self.__store_rpath_variant(ref_base_id, compat_version, ref_basename)

    # Use a loop to iteratively search as deep as needed into any transitive dependencies which are found. But we use
    # files_to_search to mark the files we've already examined and avoid duplicate work.
    while True:
      files_to_search: list[str] = [path for path, searched in libs_searched.items() if not searched]
      if not files_to_search:
        break

      for file_path in files_to_search:
        libs_searched[file_path] = True

        base_tuple = parse_base(file_path)
        if not base_tuple:
          continue
        (base_name, base_id) = base_tuple
        # See notes for blacklist above
        if base_id in ID_BLACKLIST:
          print(f'File is in blacklist, skipping: {file_path}')
          continue

        if self.log_verbose:
          print(f'Scanning: {file_path}')
        otool_find_lib_refs(file_path, handle_nix_store, handle_rpath, print_all=print_all)

  # --merge-architectures
  # --------------------------------------------------------------------------
  def merge_architectures(self, archroot0: str, archroot1: str):
    print(f'🔍 Merging binaries across architectures')

    def merge_bin(basename, path0, path1, dst_dir):
      arm64 = ''
      x86_64 = ''
      for filename in [path0, path1]:
        stdoutput = subprocess.run(['lipo', '-info', filename], capture_output=True, text=True).stdout
        if stdoutput.startswith('Non-fat'):
          if 'x86_64' in stdoutput:
            x86_64 = filename
          elif 'arm64' in stdoutput:
            arm64 = filename
          else:
            print(f'⚠️ Failed to parse lipo -info for non-fat file, skipping: {filename}')
            continue
        elif ('Architectures in the fat file' in stdoutput) and ('arm64' in stdoutput) and ('x86_64' in stdoutput):
          # If only one arch available, leave it alone
          x86_64 = filename
          arm64 = filename
          break
        else:
          print(f'⚠️ Failed to parse lipo -info for file, skipping: {filename}')
          continue

      if not arm64 or not x86_64:
        print(f'✅ Skipping single-arch {basename}')
        return

      tmpfile=f'{basename}.universal.tmp'

      # Use copy2 to preserve all file metadata with the copy
      if arm64 == x86_64:
        # Already universal binary
        print(f'✅ Already dual-arch: {basename}')
        shutil.copy2(arm64, tmpfile)
      else:
        print(f'🔨 Merging {basename}')
        subprocess.run(['lipo', '-create', '-arch', 'arm64', arm64, '-arch', 'x86_64', x86_64, '-output', tmpfile])

      dst_path = os.path.join(dst_dir, basename)
      shutil.copy2(tmpfile, dst_path)

    # Merge lib dirs
    libs0 = os.path.join(archroot0, APP_FRAMEWORKS_RELPATH)
    libs1 = os.path.join(archroot1, APP_FRAMEWORKS_RELPATH)

    def merge_lib(lib_basename, _):
      path0 = os.path.join(libs0, lib_basename)
      path1 = os.path.join(libs1, lib_basename)
      print(f'Merging libs in: [{path0}, {path1}]')
      merge_bin(lib_basename, path0, path1, self.lib_dir_path)

    for_all_libs_in_lib_dir(self.lib_dir_path, merge_lib)

    # Merge executable dirs

    exe0 = os.path.join(archroot0, APP_FRAMEWORKS_RELPATH)
    exe1 = os.path.join(archroot1, APP_FRAMEWORKS_RELPATH)

    def merge_exe(exe_basename, _):
      path0 = os.path.join(exe0, exe_basename)
      path1 = os.path.join(exe1, exe_basename)
      print(f'Merging executables in: [{path0}, {path1}]')
      merge_bin(exe_basename, path0, path1, self.executable_dir_path)

    for_all_executables_in_executable_dir(self.executable_dir_path, merge_exe)

    print(f'🔍 Merging binaries across architectures: done')


# Class: CanonicalNameDB
# This class is responsible for determining the canonical name for each lib based on the metadata in LibMetaDB, and then
# performing operations related to the canonical names, such as copying libs to libStaging with their canonical names,
# rewriting references to use the canonical names, and adding missing LC_RPATH entries.
class CanonicalNameDB:
  lib_db: LibMetaDB

  # Map: canonical_name_map = {base_id: {compat_version: canonical_name}}
  # Note: all versions must be simplified using simplify_version()! Otherwise string-based comparisons will fail.
  canonical_name_map: dict[str, dict[str, str]] = {}

  # The data in this class is all derived from lib_db. An instance of this class should not be created until after
  # lib_db is fully populated.
  def __init__(self, lib_db: LibMetaDB):
    self.lib_db = lib_db

    for base_id, variants_map in self.lib_db.name_variants_map.items():
      usr_lib_entry = USR_LIB_WHITELIST.get(base_id, None)
      if usr_lib_entry:
        popped = variants_map.pop(usr_lib_entry[0], '')
        if popped:
          print(f'Is provided by macOS; skipping "{base_id}", version {usr_lib_entry[0]}: {popped}')

      lib_version_count = len(variants_map)
      if lib_version_count == 0:
        # Skip
        continue
      if lib_version_count > 1:
        # We can't handle this currently, but it should not happen
        print(f'⚠️ ERROR: unexpectedly found multiple remaining versions ({lib_version_count}) for {base_id}! Exiting!')
        sys.exit(99)
      variant_compat_ver, variant_subversions_map = next(iter(variants_map.items()))

      # Determine the best canonical name (higher, most specific version)
      best_variant_name: str = ''
      best_variant_version_split: list[str] = []
      for variant_name in variant_subversions_map.keys():
        variant_name_split = variant_name.split('.')
        if len(variant_name_split) < 2:
          print(f'⚠️ ERROR: failed to parse version from name, skipping: {variant_name}')
          continue
        last_elem = variant_name_split[-1]
        if last_elem != "dylib" and last_elem != "so":
          print(f'⚠️ ERROR: failed to parse version from name, skipping: {variant_name}')
          continue
        variant_version_split = variant_name_split[1:-1]

        if not best_variant_version_split:
          best_variant_name = variant_name
          best_variant_version_split = variant_version_split
          continue

        i = 0
        while i < len(variant_version_split):
          if (i >= len(best_variant_version_split)) or (variant_version_split[i] > best_variant_version_split[i]):
            best_variant_name = variant_name
            best_variant_version_split = variant_version_split
            break
          i += 1

      canonical_name: str = best_variant_name
      canonical_versions_map: dict[str, str] = self.canonical_name_map.get(base_id, dict())
      canonical_versions_map[variant_compat_ver] = canonical_name
      self.canonical_name_map[base_id] = canonical_versions_map

  def __get_canonical_name(self, base_id: str, compat_version: str) -> Optional[str]:
    canonical_versions_map: dict[str, str] = self.canonical_name_map.get(base_id, {})
    if not canonical_versions_map:
      # Try rpaths
      canonical_versions_map = self.lib_db.rpaths_map.get(base_id, {})
      if not canonical_versions_map:
        print(f'⚠️ Could not find any versions for id={base_id} in canonical name map or rpaths map!')
        return None
    canonical_name = canonical_versions_map.get(compat_version, '')
    if not canonical_name:
      print(f'⚠️ Could not find canonical name for id={base_id} compatVersion={compat_version}')
      return None
    return canonical_name

  def __for_all_canonical_names(self, handler: Callable[[str, str, str], None]):
    for base_id, canonical_versions_map in self.canonical_name_map.items():
      variants_map: dict[str, dict[str, str]] = self.lib_db.name_variants_map[base_id]
      for compat_version, canonical_name in canonical_versions_map.items():
        variant_subversions_map: dict[str, str] = variants_map[compat_version]
        src_path: str = variant_subversions_map.get(canonical_name, '')
        if not src_path:
          continue

        handler(canonical_name, compat_version, src_path)

  # --canonicalize
  # --------------------------------------------------------------------------
  def canonicalize_libs(self, prune: bool):
    lib_dir = self.lib_db.lib_dir_path
    executable_dir = self.lib_db.executable_dir_path

    print(f"Canonicalizing libs in {lib_dir}…")
    # Create libStaging, then copy all libs to be processed into it.
    # This side-steps any thorny issues which might be caused by symlinks, makes purging Frameworks directory easier.
    lib_staging_dir_path = os.path.join(lib_dir, '../libStaging')
    os.makedirs(lib_staging_dir_path, exist_ok=True)
    print(f'Copying libs into {lib_staging_dir_path}')

    # Total count of libs copied, with different versions of the same lib counted as multiple.
    copied_libs_count: int = 0

    def copy_to_cname(canonical_name: str, compat_version: str, src_path: str):
      print(f'Canonical name for v{compat_version} = {canonical_name} → {src_path}')
      dst_path = os.path.join(lib_staging_dir_path, canonical_name)
      shutil.copyfile(src_path, dst_path)
      nonlocal copied_libs_count
      copied_libs_count += 1

    self.__for_all_canonical_names(copy_to_cname)
    print(f'Copied {copied_libs_count} libs into {lib_staging_dir_path}')

    # (Optional if "--prune" is specified). Removes unused lib files and links from Frameworks directory.
    # Note: this is not recursive. Sparkle.framework and any other directories will be untouched.
    # This step should not be used when building the IINA universal binary because arch-specific libs which have
    # already been processed may not be present in our data structures, and thus not moved to libStaging,
    # but they would still be deleted from Frameworks if --prune is used.
    if prune:
      print(f'✂️ Removing old lib files and links from {lib_dir}')
      all_children: map[tuple[str, str]] = map(lambda name: (name, os.path.join(lib_dir, name)), os.listdir(lib_dir))
      old_lib_links = [child for child in all_children if os.path.islink(child[1])]
      for link_basename, link_path in old_lib_links:
        if link_basename.startswith('.libiconv'):
          print(f'Will not remove lib file: {link_path}')
        else:
          os.unlink(link_path)

      for oldlib_basename, oldlib_path in ls_files_in_dir(lib_dir):
        if oldlib_basename.startswith('.libiconv'):
          print(f'Will not remove lib file: {oldlib_basename}')
        else:
          os.remove(oldlib_path)

    # Second pass. Add missing LC_RPATH entries, rewrite lib references to use @rpath & canonical names.

    def handle_nix_store(current_file_path, ref_path, compat_version, _):
      base_tuple = parse_base(ref_path)
      if not base_tuple:
        return
      (_, base_id) = base_tuple
      replacement_path = ''
      # First check for built-in system libraries which are also provided by Nix, but we want to point them to the
      # system versions instead of the Nix versions to avoid packaging issues & to save space.
      usr_lib_entry = USR_LIB_WHITELIST.get(base_id, None)
      if usr_lib_entry and compat_version == usr_lib_entry[0]:
        replacement_path = usr_lib_entry[1]
      else:
        sub_canonical_name = self.__get_canonical_name(base_id, compat_version)
        if not sub_canonical_name:
          return
        replacement_path = f'@rpath/{sub_canonical_name}'
      print(f"🔗 Repointing subdep for {os.path.basename(current_file_path)}: {ref_path} → {replacement_path}")
      rewrite_lib_reference(ref_path, replacement_path, current_file_path)

    # Process the libs in libStaging directory.
    # After each file is processed, it is moved from libStaging to Frameworks.
    print(f'🔧 Normalizing libs in {lib_staging_dir_path} & moving each to {os.path.basename(lib_dir)}')
    def normalize_lib(lib_basename, lib_path):
      print(f'Processing: {lib_basename}')
      print(f"✏️ Setting install_name id on {lib_basename}")
      subprocess.run(['install_name_tool', '-id', f'@rpath/{lib_basename}', lib_path])
      fix_lc_rpath(lib_path)
      otool_find_lib_refs(lib_path, handle_nix_store)

      shutil.move(lib_path, os.path.join(lib_dir, lib_basename))

    for_all_libs_in_lib_dir(lib_staging_dir_path, normalize_lib)

    # Remove libStaging now that all libs have been transferred.
    shutil.rmtree(lib_staging_dir_path)

    # Now process the executable binaries in MacOS directory.
    print(f'🔧 Normalizing executables in {executable_dir}')
    def normalize_exe(exe_base_name, exe_path):
      print(f'Processing: {exe_base_name}')
      fix_lc_rpath(exe_path)
      otool_find_lib_refs(exe_path, handle_nix_store)

    for_all_executables_in_executable_dir(executable_dir, normalize_exe)

    print(f"Canonicalizing libs: done")


# MAIN
# --------------------------------------------------------------------------

def main():
  arg_parser: argparse.ArgumentParser = make_arg_parser()
  try:
    args = arg_parser.parse_args()
  except SystemExit:
    # argparse already prints the error; exit gracefully
    sys.exit(1)

  lib_dir = args.lib_dir
  executable_dir = args.executable_dir
  log_verbose = args.verbose
  if log_verbose:
    print(f'Parsed arguments: {args}')
    print(f'Verbose logging enabled')

  # First pass. Scan all libs with otool, collecting dependency metadata to populate lib_db
  lib_db = LibMetaDB(lib_dir_path=lib_dir, executable_dir_path=executable_dir, log_verbose=log_verbose)
  lib_db.populate_from_disk(print_all=args.print_only)

  for base_id, variants in lib_db.name_variants_map.items():
    print(f'Variants of {base_id}: {variants}')

  # Now compile the canonical name database, which will determine the best variant for each lib and store the
  # canonical name for each version.
  cname_db = CanonicalNameDB(lib_db)

  if args.print_only:
    print(f"⚠️ Exiting script now without modifying any files, as --print-only arg was provided.")
  else:
    if args.merge_architectures:
      if not args.archroot0 or not args.archroot1:
        print(f'⚠️ Both --archroot0 and --archroot1 are required when --merge-architectures is given')
        exit(1)

      lib_db.merge_architectures(args.archroot0, args.archroot1)

    if args.canonicalize:
      cname_db.canonicalize_libs(prune=args.prune)

if __name__ == '__main__':
    main()
