extension SettingsLocalization.Key {
  static let enableLoggingLabel = SettingsLocalization.Key("enableLogging.label")
  static let useMpvOsdLabel = SettingsLocalization.Key("useMpvOsd.label")
  static let useUserDefinedConfDirLabel = SettingsLocalization.Key("useUserDefinedConfDir.label")
  static let text_AdditionalMpvOptions = SettingsLocalization.Key("$AdditionalMpvOptions")
  static let enableAdvancedSettingsLabel = SettingsLocalization.Key("enableAdvancedSettings.label")
  static let text_Name = SettingsLocalization.Key("$Name")
  static let enableAdvancedSettingsDesc = SettingsLocalization.Key("enableAdvancedSettings.desc")
  static let text_OpenLogDirectory = SettingsLocalization.Key("$OpenLogDirectory")
  static let text_Choose = SettingsLocalization.Key("$Choose")
  static let text_Value = SettingsLocalization.Key("$Value")
  static let logLevelLabel = SettingsLocalization.Key("logLevel.label")
  static let text_Logging = SettingsLocalization.Key("$Logging")
  static let text_MPVSettings = SettingsLocalization.Key("$MPVSettings")
}
