extension SettingsLocalization.Key {
  static let text_OSDFont = SettingsLocalization.Key("$OSDFont")
  static let text_OSDDisplay = SettingsLocalization.Key("$OSDDisplay")
  static let text_OSDBar = SettingsLocalization.Key("$OSDBar")
  static let osdFontLabel = SettingsLocalization.Key("osdFont.label")
  static let osdFontDesc = SettingsLocalization.Key("osdFont.desc")
  static let osdFontSizeLabel = SettingsLocalization.Key("osdFontSize.label")
  static let osdFontSizeDesc = SettingsLocalization.Key("osdFontSize.desc")
  static let osdDurationLabel = SettingsLocalization.Key("osdDuration.label")
  static let osdDurationDesc = SettingsLocalization.Key("osdDuration.desc")
  static let osdPlayingMsgDurationLabel = SettingsLocalization.Key("osdPlayingMsgDuration.label")
  static let osdPlayingMsgDurationDesc = SettingsLocalization.Key("osdPlayingMsgDuration.desc")
  static let osdPlayingMsgLabel = SettingsLocalization.Key("osdPlayingMsg.label")
  static let osdOnSeekLabel = SettingsLocalization.Key("osdOnSeek.label")
  static let oscLabel = SettingsLocalization.Key("osc.label")
  static let oscDesc = SettingsLocalization.Key("osc.desc")
  static let osdBarHLabel = SettingsLocalization.Key("osdBarH.label")
  static let osdBarHDesc = SettingsLocalization.Key("osdBarH.desc")
  static let osdBarBorderSizeLabel = SettingsLocalization.Key("osdBarBorderSize.label")
  static let osdBarBorderSizeDesc = SettingsLocalization.Key("osdBarBorderSize.desc")
  static let osdBorderSizeLabel = SettingsLocalization.Key("osdBorderSize.label")
  static let osdBorderSizeDesc = SettingsLocalization.Key("osdBorderSize.desc")
  static let osdFractionsLabel = SettingsLocalization.Key("osdFractions.label")
}
