extension SettingsLocalization.Key {
  static let text_ClearSavedPlaybackProgress = SettingsLocalization.Key("$ClearSavedPlaybackProgress")
  static let text_DeleteAllPlaybackHistories = SettingsLocalization.Key("$DeleteAllPlaybackHistories")
  static let text_Cleared = SettingsLocalization.Key("$Cleared")
  static let text_OpenLinksOrCurrentWebpage = SettingsLocalization.Key("$OpenLinksOrCurrentWebpage")
  static let text_OK = SettingsLocalization.Key("$OK")
  static let text_ClearPlaybackHistory = SettingsLocalization.Key("$ClearPlaybackHistory")
  static let text_DefaultApplication = SettingsLocalization.Key("$DefaultApplication")
  static let text_ClearCache = SettingsLocalization.Key("$ClearCache")
  static let text_SetIINAAsTheDefault = SettingsLocalization.Key("$SetIINAAsTheDefault")
  static let text_Firefox = SettingsLocalization.Key("$Firefox")
  static let text_ClearThumbnailCache = SettingsLocalization.Key("$ClearThumbnailCache")
  static let text_Cancel = SettingsLocalization.Key("$Cancel")
  static let text_RestoreAlerts = SettingsLocalization.Key("$RestoreAlerts")
  static let text_RestoreSuppressedAlerts = SettingsLocalization.Key("$RestoreSuppressedAlerts")
  static let text_Restored = SettingsLocalization.Key("$Restored")
  static let text_RestoreAllAlertsThat = SettingsLocalization.Key("$RestoreAllAlertsThat")
  static let text_Calculating = SettingsLocalization.Key("$Calculating")
  static let text_CurrentThumbnailCache = SettingsLocalization.Key("$CurrentThumbnailCache")
  static let text_PleaseSelectTheMediaTypes = SettingsLocalization.Key("$PleaseSelectTheMediaTypes")
  static let text_Chrome = SettingsLocalization.Key("$Chrome")
  static let text_BrowserExtensions = SettingsLocalization.Key("$BrowserExtensions")
  static let text_GetBrowserExtensionsForIINA = SettingsLocalization.Key("$GetBrowserExtensionsForIINA")
  static let text_DeleteAllWatchLater = SettingsLocalization.Key("$DeleteAllWatchLater")
}
