extension SettingsLocalization.Key {
  static let text_Install = SettingsLocalization.Key("$Install")
  static let text_Author = SettingsLocalization.Key("$Author")
  static let text_Email = SettingsLocalization.Key("$Email")
  static let text_Help = SettingsLocalization.Key("$Help")
  static let text_PleaseEnterTheFullURL = SettingsLocalization.Key("$PleaseEnterTheFullURL")
  static let text_Website = SettingsLocalization.Key("$Website")
  static let text_InstalledPlugins = SettingsLocalization.Key("$InstalledPlugins")
  static let text_ShowInFinder = SettingsLocalization.Key("$ShowInFinder")
  static let text_InstallFromGitHub = SettingsLocalization.Key("$InstallFromGitHub")
  static let text_YouCanInstallANew = SettingsLocalization.Key("$YouCanInstallANew")
  static let text_Reload = SettingsLocalization.Key("$Reload")
  static let text_Identifier = SettingsLocalization.Key("$Identifier")
  static let text_DefaultPlugins = SettingsLocalization.Key("$DefaultPlugins")
  static let text_FailedToLoadThePage = SettingsLocalization.Key("$FailedToLoadThePage")
  static let text_Source = SettingsLocalization.Key("$Source")
  static let text_InstallPackage = SettingsLocalization.Key("$InstallPackage")
  static let text_Plugins = SettingsLocalization.Key("$Plugins")
  static let text_Uninstall = SettingsLocalization.Key("$Uninstall")
  static let text_InstallANewPluginFrom = SettingsLocalization.Key("$InstallANewPluginFrom")
  static let text_About = SettingsLocalization.Key("$About")
}
