extension SettingsLocalization.Key {
  static let hardwareDecoderLabel = SettingsLocalization.Key("hardwareDecoder.label")
  static let hardwareDecoderDesc = SettingsLocalization.Key("hardwareDecoder.desc")
  static let hardwareDecoderItem0 = SettingsLocalization.Key("hardwareDecoder.items.0")
  static let hardwareDecoderItem1 = SettingsLocalization.Key("hardwareDecoder.items.1")
  static let hardwareDecoderItem2 = SettingsLocalization.Key("hardwareDecoder.items.2")
  static let forceDedicatedGPULabel = SettingsLocalization.Key("forceDedicatedGPU.label")
  static let forceDedicatedGPUDesc = SettingsLocalization.Key("forceDedicatedGPU.desc")
  static let loadIccProfileLabel = SettingsLocalization.Key("loadIccProfile.label")
  static let loadIccProfileDesc = SettingsLocalization.Key("loadIccProfile.desc")
  static let enableHdrSupportLabel = SettingsLocalization.Key("enableHdrSupport.label")
  static let enableHdrSupportDesc = SettingsLocalization.Key("enableHdrSupport.desc")
  static let enableToneMappingLabel = SettingsLocalization.Key("enableToneMapping.label")
  static let toneMappingTargetPeakLabel = SettingsLocalization.Key("toneMappingTargetPeak.label")
  static let toneMappingTargetPeakDesc = SettingsLocalization.Key("toneMappingTargetPeak.desc")
  static let toneMappingAlgorithmLabel = SettingsLocalization.Key("toneMappingAlgorithm.label")
  static let toneMappingAlgorithmItem0 = SettingsLocalization.Key("toneMappingAlgorithm.items.0")
  static let toneMappingAlgorithmItem1 = SettingsLocalization.Key("toneMappingAlgorithm.items.1")
  static let toneMappingAlgorithmItem2 = SettingsLocalization.Key("toneMappingAlgorithm.items.2")
  static let toneMappingAlgorithmItem3 = SettingsLocalization.Key("toneMappingAlgorithm.items.3")
  static let toneMappingAlgorithmItem4 = SettingsLocalization.Key("toneMappingAlgorithm.items.4")
  static let toneMappingAlgorithmItem5 = SettingsLocalization.Key("toneMappingAlgorithm.items.5")
  static let toneMappingAlgorithmItem6 = SettingsLocalization.Key("toneMappingAlgorithm.items.6")
  static let toneMappingAlgorithmItem7 = SettingsLocalization.Key("toneMappingAlgorithm.items.7")
  static let text_Decoding = SettingsLocalization.Key("$Decoding")
  static let text_ColorHDR = SettingsLocalization.Key("$ColorHDR")
  static let text_LiveText = SettingsLocalization.Key("$LiveText")
  // Also used by the audio page for the audio threads input
  static let videoThreadsLabel = SettingsLocalization.Key("videoThreads.label")
  static let videoThreadsDesc = SettingsLocalization.Key("videoThreads.desc")
  static let text_Video = SettingsLocalization.Key("$Video")
  static let text_nits = SettingsLocalization.Key("$nits")
  static let text_DefaultAuto = SettingsLocalization.Key("$DefaultAuto")
  static let text_EnableToneMappingImagesOnto = SettingsLocalization.Key("$EnableToneMappingImagesOnto")
  static let text_Algorithm = SettingsLocalization.Key("$Algorithm")
  static let text_AlgorithmToUseForTone = SettingsLocalization.Key("$AlgorithmToUseForTone")
  static let text_ReplayGain = SettingsLocalization.Key("$ReplayGain")
}
